version: '2'
services:
  recaleur-server:
    image: registry.gitlab.com/recalbox/ops/recaleur:2.3.0
    environment:
      LOGSTASH_TAGS: recaleur
    command:
    - --response
    - ${RECALEUR_RESPONSE}
    - --canary
    - ${RECALEUR_CANARY}
    - --path
    - ${RECALEUR_PATH}
    - --responsedelta
    - ${RECALEUR_DELTA}
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 50m
    labels:
      archive: true
      io.rancher.scheduler.affinity:host_label: archive=true