################################################################################
#
# libcross2d
#
################################################################################

LIBCROSS2D_VERSION = 20
LIBCROSS2D_REPO = Cpasjuste
LIBCROSS2D_SITE = /opt/recalbox/recalbox-rpi3/libcross2d
LIBCROSS2D_SITE_METHOD = local
#$(call github,$(LIBCROSS2D_REPO),libcross2d,$(LIBCROSS2D_VERSION))
LIBCROSS2D_LICENSE = GPL3
LIBCROSS2D_DEPENDENCIES = sdl2 glm freetype config zlib

LIBCROSS2D_CONF_OPTS = -DPLATFORM_RPI3_64=ON -DOPTION_RECALBOX=ON -DSYSROOT="$(STAGING_DIR)"
LIBCROSS2D_CONF_OPTS += -DCMAKE_C_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LIBCROSS2D_CONF_OPTS += -DCMAKE_C_ARCHIVE_FINISH=true
LIBCROSS2D_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LIBCROSS2D_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_FINISH=true
LIBCROSS2D_CONF_OPTS += -DCMAKE_AR="$(TARGET_CC)-ar"
LIBCROSS2D_CONF_OPTS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
LIBCROSS2D_CONF_OPTS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
LIBCROSS2D_CONF_OPTS += -DCMAKE_LINKER="$(TARGET_LD)"
LIBCROSS2D_CONF_OPTS += -DCMAKE_C_FLAGS="$(COMPILER_COMMONS_CFLAGS_EXE)"
LIBCROSS2D_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(COMPILER_COMMONS_CXXFLAGS_EXE)"
LIBCROSS2D_CONF_OPTS += -DCMAKE_LINKER_EXE_FLAGS="$(COMPILER_COMMONS_LDFLAGS_EXE)"

$(eval $(cmake-package))
