#!/bin/bash

do_start() {
    # recalbox background
    test -e /dev/fb0 && fbv -f -i /recalbox/system/resources/splash/logo-version.png

    # Wait for emulationstation or Kodi, but not more than 20 seconds
    count=0
    while [[ ! -f "/tmp/emulationstation.ready" && ! -e "/var/run/kodi.msg" && $count -lt 20 ]]; do
        sleep 1
        ((count++))
    done
}

case "$1" in
    start)
        do_start &
        ;;
    stop)
	   ;;
    restart|reload)
	   ;;
    *)
esac

exit $?
