#!/bin/bash

if test "$1" != "stop"
then
  exit 0
fi

scr_msg() {
	printf "\r%20s%10s" "${1}" " " > /dev/tty0 # with spaces at the begining for screen not displaying the left ; and spaces on right to erase old msg
}
clear > /dev/tty0
(echo;echo;echo;echo;echo) > /dev/tty0
scr_msg "It is now safe to power off Recalbox"
