#!/bin/ash

if [ "$1" != "start" ]; then
  exit 0
fi

# force a date over 1980 because of fat32 (to make rsync to work)
currentYear=$(date +%Y)
if [ ${currentYear} -lt 1980 ]; then
  date -s '1980-01-01 01:00:00'
fi
