#!/bin/sh

# mount the /boot partition in read only

function shouldUpdate {
  grep "dtparam=audio=on" /boot/config.txt && return 1
  return 0
}

function updateBoot {
  sed -i '/^dtparam=/{h;s/=.*/=audio=on/};${x;/^$/{s//dtparam=audio=on/;H};x}' /boot/config.txt
}

case "$1" in
  start)
      BOOTPART=$(/recalbox/scripts/recalbox-part.sh boot)
      if test $? -ne 0
      then
	  exit 1
      fi
      mount | cut -d ' ' -f 3 | grep -q "/boot" || mount "${BOOTPART}" -o ro /boot || exit 1
      # Update /boot/config.txt if needed
      if shouldUpdate
      then
          mount "${BOOTPART}" /boot -o remount,rw || exit 1
          updateBoot
          mount -o remount,ro /boot || exit 1
      fi
      ;;
  stop)
      #Backup recalbox.conf to /boot partition
      mount -o remount,rw /boot
      cp /recalbox/share/system/recalbox.conf /boot/recalbox-backup.conf
      sed -i '1s/^/#THIS IS A BACKUP OF RECALBOX.CONF\n#PLEASE DO NOT MAKE ANY CHANGE HERE !!!\n\n\n/' /boot/recalbox-backup.conf
      mount -o remount,ro /boot
      sync
      recallog "recalbox.conf saved to /boot partition"
      umount /boot || exit 1
      ;;
  *)
      echo "Usage: $0 {start|stop}"
      exit 1
esac

exit 0
