#!/bin/bash

# Function to create connmann wifi profiles based on user settings

rb_wifi_boot_configure() {
        [ "$1" = "1" ] && X="" || X="$1"
        settings_ssid=`egrep "^wifi${X}.ssid" /boot/recalbox-backup.conf|sed "s/wifi${X}.ssid=//g"`
        settings_key=`egrep "^wifi${X}.key" /boot/recalbox-backup.conf|sed "s/wifi${X}.key=//g"`
        settings_file="/var/lib/connman/recalbox_wifi${X}.config"
        [ "$1" = "1" ] && settings_name="default" || settings_name="${X}"


        settings_ip=`egrep "^wifi${X}.ip" /boot/recalbox-backup.conf|sed "s/wifi${X}.ip=//g"`
        settings_gateway=`egrep "^wifi${X}.gateway" /boot/recalbox-backup.conf|sed "s/wifi${X}.gateway=//g"`
        settings_netmask=`egrep "^wifi${X}.netmask" /boot/recalbox-backup.conf|sed "s/wifi${X}.netmask=//g"`

	settings_manual_section=""
        if [[ "$settings_ip" != "" ]] && \
	   [[ "$settings_gateway" != "" ]] && \
	   [[ "$settings_netmask" != "" ]] ;then
	   settings_manual_section="
IPv4=${settings_ip}/${settings_netmask}/${settings_gateway}"
	fi
        if [[ "$settings_ssid" != "" ]] ;then

	recallog "Recovering wifi for SSID: $settings_ssid"

        mkdir -p "/var/lib/connman"
        cat > "${settings_file}" <<EOF
[global]
Name=recalbox

[service_recalbox_${settings_name}]
Type=wifi
Name=${settings_ssid}${settings_manual_section}
EOF
        if test "${settings_key}" != ""
        then
            settings_key_dec=$(/recalbox/scripts/recalbox-encode.sh decode "${settings_key}")
            echo "Passphrase=${settings_key_dec}" >> "${settings_file}"
	fi
    fi
}

# Main

case "$1" in
  start)
	if [ -f /boot/recalbox-backup.conf ]
	then
		if [ `egrep "^wifi.enabled" /boot/recalbox-backup.conf|sed "s/wifi.enabled=//g"` -ne 0  ]
		then
			recallog "Wifi option enabled, trying to configure"
			sleep 1 # wait a bit to be sure tmpfs is initialized
			for i in {1..3}; do
				rb_wifi_boot_configure $i&
			done
			sleep 1 # wait a bit, otherwise, connman is not really started
			/usr/bin/connmanctl enable wifi || exit 1
			settings_region=`egrep "^wifi.region" /boot/recalbox-backup.conf|sed "s/wifi.region=//g"`
			if [[ "$settings_region" != "" ]] ;then
				recallog "Wifi region: ${settings_region}"
				/usr/sbin/iw reg set "${settings_region}"
			fi
			/usr/bin/connmanctl scan   wifi || exit 1
		else
			recallog "Wifi option disabled"
		fi
	else
		recallog "/boot/recalbox-backup.conf not found"
	fi

	# If share over network, let's add a timeout of 10 seconds (max) for slow networks
	if [ `grep -c "^sharedevice=NETWORK$" /boot/recalbox-boot.conf` -ne 0 ]
	then
		try=0
		until [ ! $try -lt 10 ]
		do
			if [ `ifconfig |grep -v "127.0.0.1"|grep -c "inet addr"` -gt 0 ]
			then
				break # Of course if network is OK, don't wait anymore!
			fi
			sleep 1
			try=`expr $try + 1`
		done
	fi
	;;
  stop)
	;;
  *)
esac

exit $?
