#!/bin/sh

if test "$1" == "start"
then
  python2.7 /recalbox/system/hardware/case/manage.pyc "" 1 1 1
  if [[ -f /tmp/.install.png ]] ; then
  	killall fbv
  	fbv -s 1 -f -e -i -r /recalbox/system/resources/splash/black.png
    fbv -f -i /recalbox/system/resources/splash/logo-version.png &
  fi  
fi

