################################################################################
#
# recalbox-romfs-amiga1200
#
################################################################################

# Package generated with :
# ./scripts/linux/empack.py --system amiga1200 --extension '.adf .Adf .ADF .ipf .IPF .Ipf .lha .LHA .lhz .LHZ .lzx .LZX .zip .ZIP .rp9 .RP9 .dms .DMS .fdi .FDI .hdf .HDF .hdz .HDZ .m3u .M3U' --fullname 'Amiga 1200' --platform amiga --theme amiga1200 amiberry:amiberry:BR2_PACKAGE_AMIBERRY libretro:puae:BR2_PACKAGE_LIBRETRO_UAE

# Name the 3 vars as the package requires
RECALBOX_ROMFS_AMIGA1200_SOURCE = 
RECALBOX_ROMFS_AMIGA1200_SITE = 
RECALBOX_ROMFS_AMIGA1200_INSTALL_STAGING = NO
# Set the system name
SYSTEM_NAME_AMIGA1200 = amiga1200
SYSTEM_XML_AMIGA1200 = $(@D)/$(SYSTEM_NAME_AMIGA1200).xml
# System rom path
SOURCE_ROMDIR_AMIGA1200 = $(RECALBOX_ROMFS_AMIGA1200_PKGDIR)/roms

# CONFIGGEN_STD_CMD is defined in recalbox-romfs, so take good care that
# variables are global across buildroot


ifneq ($(BR2_PACKAGE_AMIBERRY)$(BR2_PACKAGE_LIBRETRO_UAE),)
define CONFIGURE_MAIN_AMIGA1200_START
	$(call RECALBOX_ROMFS_CALL_ADD_SYSTEM,$(SYSTEM_XML_AMIGA1200),Amiga 1200,$(SYSTEM_NAME_AMIGA1200),.adf .Adf .ADF .ipf .IPF .Ipf .lha .LHA .lhz .LHZ .lzx .LZX .zip .ZIP .rp9 .RP9 .dms .DMS .fdi .FDI .hdf .HDF .hdz .HDZ .m3u .M3U,amiga,amiga1200)
endef

ifneq ($(BR2_PACKAGE_AMIBERRY)$(BR2_PACKAGE_LIBRETRO_UAE),)
define CONFIGURE_AMIGA1200_AMIBERRY_START
	$(call RECALBOX_ROMFS_CALL_START_EMULATOR,$(SYSTEM_XML_AMIGA1200),amiberry)
endef
ifeq ($(BR2_PACKAGE_AMIBERRY),y)
define CONFIGURE_AMIGA1200_AMIBERRY_AMIBERRY_DEF
	$(call RECALBOX_ROMFS_CALL_ADD_CORE,$(SYSTEM_XML_AMIGA1200),amiberry)
endef
endif

define CONFIGURE_AMIGA1200_AMIBERRY_END
	$(call RECALBOX_ROMFS_CALL_END_EMULATOR,$(SYSTEM_XML_AMIGA1200))
endef
endif

ifneq ($(BR2_PACKAGE_AMIBERRY)$(BR2_PACKAGE_LIBRETRO_UAE),)
define CONFIGURE_AMIGA1200_LIBRETRO_START
	$(call RECALBOX_ROMFS_CALL_START_EMULATOR,$(SYSTEM_XML_AMIGA1200),libretro)
endef
ifeq ($(BR2_PACKAGE_LIBRETRO_UAE),y)
define CONFIGURE_AMIGA1200_LIBRETRO_PUAE_DEF
	$(call RECALBOX_ROMFS_CALL_ADD_CORE,$(SYSTEM_XML_AMIGA1200),puae)
endef
endif

define CONFIGURE_AMIGA1200_LIBRETRO_END
	$(call RECALBOX_ROMFS_CALL_END_EMULATOR,$(SYSTEM_XML_AMIGA1200))
endef
endif



define CONFIGURE_MAIN_AMIGA1200_END
	$(call RECALBOX_ROMFS_CALL_END_SYSTEM,$(SYSTEM_XML_AMIGA1200),$(SOURCE_ROMDIR_AMIGA1200),$(@D))
endef
endif

define RECALBOX_ROMFS_AMIGA1200_CONFIGURE_CMDS
	$(CONFIGURE_MAIN_AMIGA1200_START)
	$(CONFIGURE_AMIGA1200_AMIBERRY_START)
	$(CONFIGURE_AMIGA1200_AMIBERRY_AMIBERRY_DEF)
	$(CONFIGURE_AMIGA1200_AMIBERRY_END)
	$(CONFIGURE_AMIGA1200_LIBRETRO_START)
	$(CONFIGURE_AMIGA1200_LIBRETRO_PUAE_DEF)
	$(CONFIGURE_AMIGA1200_LIBRETRO_END)
	$(CONFIGURE_MAIN_AMIGA1200_END)
endef

$(eval $(generic-package))
