################################################################################
#
# recalbox-romfs-snes
#
################################################################################

# Package generated with :
# ./scripts/linux/empack.py --system snes --extension '.smc .sfc .SMC .SFC .mgd .MGD .zip .ZIP .7z .7Z' --fullname 'Super Nintendo Entertainment System' --platform snes --theme snes libretro:snes9x2002:BR2_PACKAGE_LIBRETRO_SNES9X2002 libretro:snes9x2005:BR2_PACKAGE_LIBRETRO_SNES9X2005 libretro:snes9x2010:BR2_PACKAGE_LIBRETRO_SNES9X2010 libretro:snes9x:BR2_PACKAGE_LIBRETRO_SNES9X

# Name the 3 vars as the package requires
RECALBOX_ROMFS_SNES_SOURCE = 
RECALBOX_ROMFS_SNES_SITE = 
RECALBOX_ROMFS_SNES_INSTALL_STAGING = NO
# Set the system name
SYSTEM_NAME_SNES = snes
SYSTEM_XML_SNES = $(@D)/$(SYSTEM_NAME_SNES).xml
# System rom path
SOURCE_ROMDIR_SNES = $(RECALBOX_ROMFS_SNES_PKGDIR)/roms

# CONFIGGEN_STD_CMD is defined in recalbox-romfs, so take good care that
# variables are global across buildroot


ifneq ($(BR2_PACKAGE_LIBRETRO_SNES9X2002)$(BR2_PACKAGE_LIBRETRO_SNES9X2005)$(BR2_PACKAGE_LIBRETRO_SNES9X2010)$(BR2_PACKAGE_LIBRETRO_SNES9X),)
define CONFIGURE_MAIN_SNES_START
	$(call RECALBOX_ROMFS_CALL_ADD_SYSTEM,$(SYSTEM_XML_SNES),Super Nintendo Entertainment System,$(SYSTEM_NAME_SNES),.smc .sfc .SMC .SFC .mgd .MGD .zip .ZIP .7z .7Z,snes,snes)
endef

ifneq ($(BR2_PACKAGE_LIBRETRO_SNES9X2002)$(BR2_PACKAGE_LIBRETRO_SNES9X2005)$(BR2_PACKAGE_LIBRETRO_SNES9X2010)$(BR2_PACKAGE_LIBRETRO_SNES9X),)
define CONFIGURE_SNES_LIBRETRO_START
	$(call RECALBOX_ROMFS_CALL_START_EMULATOR,$(SYSTEM_XML_SNES),libretro)
endef
ifeq ($(BR2_PACKAGE_LIBRETRO_SNES9X2005),y)
define CONFIGURE_SNES_LIBRETRO_SNES9X2005_DEF
	$(call RECALBOX_ROMFS_CALL_ADD_CORE,$(SYSTEM_XML_SNES),snes9x2005)
endef
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_SNES9X2010),y)
define CONFIGURE_SNES_LIBRETRO_SNES9X2010_DEF
	$(call RECALBOX_ROMFS_CALL_ADD_CORE,$(SYSTEM_XML_SNES),snes9x2010)
endef
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_SNES9X),y)
define CONFIGURE_SNES_LIBRETRO_SNES9X_DEF
	$(call RECALBOX_ROMFS_CALL_ADD_CORE,$(SYSTEM_XML_SNES),snes9x)
endef
endif

ifeq ($(BR2_PACKAGE_LIBRETRO_SNES9X2002),y)
define CONFIGURE_SNES_LIBRETRO_SNES9X2002_DEF
	$(call RECALBOX_ROMFS_CALL_ADD_CORE,$(SYSTEM_XML_SNES),snes9x2002)
endef
endif

define CONFIGURE_SNES_LIBRETRO_END
	$(call RECALBOX_ROMFS_CALL_END_EMULATOR,$(SYSTEM_XML_SNES))
endef
endif



define CONFIGURE_MAIN_SNES_END
	$(call RECALBOX_ROMFS_CALL_END_SYSTEM,$(SYSTEM_XML_SNES),$(SOURCE_ROMDIR_SNES),$(@D))
endef
endif

define RECALBOX_ROMFS_SNES_CONFIGURE_CMDS
	$(CONFIGURE_MAIN_SNES_START)
	$(CONFIGURE_SNES_LIBRETRO_START)
	$(CONFIGURE_SNES_LIBRETRO_SNES9X2005_DEF)
	$(CONFIGURE_SNES_LIBRETRO_SNES9X2010_DEF)
	$(CONFIGURE_SNES_LIBRETRO_SNES9X_DEF)
	$(CONFIGURE_SNES_LIBRETRO_SNES9X2002_DEF)
	$(CONFIGURE_SNES_LIBRETRO_END)
	$(CONFIGURE_MAIN_SNES_END)
endef

$(eval $(generic-package))