version: '2'
services:
  RANCHER_SERVICENAME:
    image: rancher/lb-service-haproxy:v0.7.5
    environment:
      HTTPERRORPAGE: |-
        HTTP/1.0 503 Service Unavailable
        Cache-Control: no-cache
        Connection: close
        Content-Type: text/html

        <html><head>
        <title>503 - Service Unavailable</title>
        <style>body { background-color: #34495E; text-align: center; font-size: 1.5rem; font-family: sans-serif; margin: 0px;} .error { color: white; margin: 2%} a{ color: white;}</style>
        </head><body>
        <div class="error">
            <h3>You found a little bug...</h3><h1>Error 503</h1><p>The service is not available, but we are already working on it.</p>
            <p>You can go back to <a href="https://www.recalbox.com">www.recalbox.com</a> or take a look at our news on the blog
            at <a href="https://www.recalbox.com/blog">www.recalbox.com/blog</a></p>
        </div>
        <div style="background-color: white"><img src="https://s3-eu-west-1.amazonaws.com/recalbox-public/503.gif"/></div>
        </body></html>
      LOGSTASH_TAGS: haproxy,archive
    entrypoint:
    - sh
    - -c
    - echo "$$HTTPERRORPAGE" > /etc/haproxy/errors/503-mycustom.http && (lb-controller.sh --controller rancher --provider haproxy)& tail -f /var/log/haproxy/traffic -f /var/log/haproxy/errors
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 300m
    ports:
    - 8443:443/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: 'true'
      io.rancher.sidekicks: RANCHER_SERVICENAME-data
  RANCHER_SERVICENAME-data:
    image: ${ARCHIVE_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 50m
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
