################################################################################
#
# pEMU
#
################################################################################

PEMU_VERSION = 5
PEMU_REPO = Cpasjuste
PEMU_SITE = /opt/recalbox/pemu
PEMU_SITE_METHOD = local
#$(call github,$(PEMU_REPO),libcross2d,$(PEMU_VERSION))
PEMU_LICENSE = GPL3
PEMU_DEPENDENCIES = sdl2 glm freetype config zlib

PEMU_CONF_OPTS = -DPLATFORM_RPI3=ON -DOPTION_RECALBOX=ON -DOPTION_BUILTIN_MINIZIP=ON -DSYSROOT="$(STAGING_DIR)"
PEMU_CONF_OPTS += -DCMAKE_C_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
PEMU_CONF_OPTS += -DCMAKE_C_ARCHIVE_FINISH=true
PEMU_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
PEMU_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_FINISH=true
PEMU_CONF_OPTS += -DCMAKE_AR="$(TARGET_CC)-ar"
PEMU_CONF_OPTS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
PEMU_CONF_OPTS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
PEMU_CONF_OPTS += -DCMAKE_LINKER="$(TARGET_LD)"
PEMU_CONF_OPTS += -DCMAKE_C_FLAGS="$(COMPILER_COMMONS_CFLAGS_EXE)"
PEMU_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(COMPILER_COMMONS_CXXFLAGS_EXE)"
PEMU_CONF_OPTS += -DCMAKE_LINKER_EXE_FLAGS="$(COMPILER_COMMONS_LDFLAGS_EXE)"

$(eval $(cmake-package))
